#!/usr/bin/env bash
#configures the Nginx server so as /redirect_me is redirectint to another page

sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-available/default
sudo service nginx restart

