#!/usr/bin/env bash
#customized Nginx response header.

sudo apt-get update
sudo apt-get install nginx -y

# create hello world page
echo "Hello World!" | sudo tee /var/www/html/index.html

# create redirection for our website
sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-available/default


# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default

# Add custom header configuration to Nginx
sudo sed -i "/^http {/a \    add_header X-Served-By $hostname;" /etc/nginx/nginx.conf

# restart web server after updating the settings
sudo service nginx restart
