#!/bin/bash

# Get the current date
current_date=$(date +'%d-%m-%Y')

# MySQL dump file name
dump_file="backup.sql"

# Compressed archive name
archive_name="${current_date}.tar.gz"

# MySQL root password
password="$1"

# Generate MySQL dump
mysqldump -u root -p"$password" --all-databases > "$dump_file"

# Create compressed archive
tar -czvf "$archive_name" "$dump_file"

# Cleanup the dump file
rm "$dump_file"

echo "MySQL backup completed: $archive_name"

