#!/usr/bin/env bash
#display the time for 12 hrs and 59 minutes
#displays hrs from 0 to 12
#displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done


